language: node_js

stages:
  # - test
  - deploy

jobs:
  include:
    # - stage: test
    #   script: skip
    - stage: deploy
      if: branch = master
      script:
        - curl -s -I -u $DEPLOY_USER "$DEPLOY_URL" > /dev/null