language: node_js

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script: skip
    - stage: deploy
      if: branch = master
      script:
        - curl -I -u $DEPLOY_USER "$DEPLOY_URL&cause=TRAVIS_JOB_ID=$TRAVIS_JOB_ID"